name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Unit test
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.13.x, 1.18.x, 1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate headers
      if: startsWith(matrix.go-version, '1.13') == false
      run: |
        go install github.com/kunalkushwaha/ltag@latest \
        && ./scripts/validate/fileheader
    - name: Test
      run: go test -v ./...
